PROGRAM MAIN
  USE ISO_C_BINDING 
  IMPLICIT NONE 
!----初期パラメタ-------------------------------------------------------

  LOGICAL :: ALCONV=.TRUE. 
  !ALCONVが.TRUE.の場合，全時間の変換を行います．ファイルサイズに注意！
  !ALCONVが.FALSE.の場合，任意に指定した時刻のデータを変換します．

  CHARACTER(128),PARAMETER :: DATPAS='../dat/' !データディレクトリパス
  CHARACTER(128),PARAMETER :: FNZETS='ZETA_S' !入力ファイル名
  CHARACTER(128),PARAMETER :: FNZETG='ZETA_G' !出力ファイル名
  CHARACTER(128),PARAMETER :: FNDIVS='DIV_S'
  CHARACTER(128),PARAMETER :: FNDIVG='DIV_G'
  CHARACTER(128),PARAMETER :: FNDPHS='DEPTH_S'
  CHARACTER(128),PARAMETER :: FNDPHG='DEPTH_G'
  CHARACTER(128),PARAMETER :: ADDON='.dat'
  INTEGER(8),PARAMETER :: JM=512 !緯度方向格子点数
  INTEGER(8),PARAMETER :: IM=1024 !経度方向格子点数
  INTEGER(8),PARAMETER :: NN=341 !切断波数
  INTEGER(8),PARAMETER :: MM=NN
  INTEGER(8),PARAMETER :: NM=NN+1
  INTEGER(8),PARAMETER :: NT=NN
  INTEGER(8),PARAMETER :: DAY=100 !計算日数
  INTEGER(8),PARAMETER :: WDAY=5 !変換したい日付
!----ISPACK用-----------------------------------------------------------
  REAL(8) :: T(IM*3/2)
  REAL(8) :: R(((MM+1)*(2*NM-MM-1)+1)/4*3+(2*NM-MM)*(MM+1)/2+MM+1)
  REAL(8) :: C((2*NT-MM+1)*(MM+1))
  REAL(8) :: D(NT+1+MM*(2*NT-MM+1),2)
  REAL(8),DIMENSION(:,:),POINTER :: P
  REAL(8),DIMENSION(:),POINTER :: W
  INTEGER(8) :: IT(IM/2)
  INTEGER(8) :: JC(MM*(2*NM-MM-1)/16+MM)
  INTEGER(8) :: L
!----データ配列---------------------------------------------------------
  REAL(8),DIMENSION(:,:),POINTER :: G
  REAL(8) :: S((2*NN+1-MM)*MM+NN+1)
  INTEGER(8) :: I
  CHARACTER(128) :: NOWDAY
!----ポインタ用---------------------------------------------------------
  TYPE(C_PTR) :: PP
  TYPE(C_PTR) :: PW
  TYPE(C_PTR) :: PG

  CALL MXALLC(PP,JM/2*(2*MM+5))
  CALL MXALLC(PG,JM*IM)
  CALL MXALLC(PW,JM*IM)
  CALL C_F_POINTER(PP, P, [JM/2,2*MM+5])  
  CALL C_F_POINTER(PG, G, [IM,JM])
  CALL C_F_POINTER(PW, W, [IM*JM])
  CALL SXINI1(MM,NM,IM,IT,T,R)
  CALL SXINI2(MM,NM,JM,1_8,P,R,JC)

  IF(ALCONV) THEN
    DO I=0,DAY
      WRITE(NOWDAY,'(I4.4)') I
      OPEN(UNIT=10,&
      FILE=TRIM(DATPAS)//TRIM(FNZETS)//TRIM(NOWDAY)//TRIM(ADDON),&
      FORM='UNFORMATTED',ACCESS='DIRECT',&
      RECL=((2*NN+1-MM)*MM+NN+1)*8,&
      CONVERT='BIG_ENDIAN',STATUS='OLD')
      READ(10,REC=1) S(:)
      WRITE(*,*) 'NOW CONVERTED DATA IS',I,'STEP'
      CALL SXTS2G(MM,NM,NN,IM,JM,S,G,IT,T,P,R,JC,W,0_8)
      OPEN(UNIT=11,&
      FILE=TRIM(DATPAS)//TRIM(FNZETG)//TRIM(NOWDAY)//TRIM(ADDON),&
      FORM='UNFORMATTED',ACCESS='DIRECT',RECL=JM*IM*8,&
      CONVERT='BIG_ENDIAN',STATUS='REPLACE')
      WRITE(11,REC=1) G(:,:)
      CLOSE(10)
      CLOSE(11)
    ENDDO
  ELSE
    WRITE(NOWDAY,'(I4.4)') WDAY
    OPEN(UNIT=10,&
    FILE=TRIM(DATPAS)//TRIM(FNZETS)//TRIM(NOWDAY)//TRIM(ADDON),&
    FORM='UNFORMATTED',ACCESS='DIRECT',&
    RECL=((2*NN+1-MM)*MM+NN+1)*8,&
    CONVERT='BIG_ENDIAN',STATUS='OLD')
    READ(10,REC=1) S(:)
    WRITE(*,*) 'NOW CONVERTED DATA IS',WDAY,'[DAY]'
    CALL SXTS2G(MM,NM,NN,IM,JM,S,G,IT,T,P,R,JC,W,0_8)
    OPEN(UNIT=11,&
    FILE=TRIM(DATPAS)//TRIM(FNZETG)//TRIM(NOWDAY)//TRIM(ADDON),&
    FORM='UNFORMATTED',ACCESS='DIRECT',RECL=JM*IM*8,&
    CONVERT='BIG_ENDIAN',STATUS='REPLACE')
    WRITE(11,REC=1) G(:,:)
    CLOSE(10)
    CLOSE(11)
  ENDIF

  IF(ALCONV) THEN
    DO I=0,DAY
      WRITE(NOWDAY,'(I4.4)') I
      OPEN(UNIT=10,&
      FILE=TRIM(DATPAS)//TRIM(FNDIVS)//TRIM(NOWDAY)//TRIM(ADDON),&
      FORM='UNFORMATTED',ACCESS='DIRECT',&
      RECL=((2*NN+1-MM)*MM+NN+1)*8,&
      CONVERT='BIG_ENDIAN',STATUS='OLD')
      READ(10,REC=1) S(:)
      WRITE(*,*) 'NOW CONVERTED DATA IS',I,'STEP'
      CALL SXTS2G(MM,NM,NN,IM,JM,S,G,IT,T,P,R,JC,W,0_8)
      OPEN(UNIT=11,&
      FILE=TRIM(DATPAS)//TRIM(FNDIVG)//TRIM(NOWDAY)//TRIM(ADDON),&
      FORM='UNFORMATTED',ACCESS='DIRECT',RECL=JM*IM*8,&
      CONVERT='BIG_ENDIAN',STATUS='REPLACE')
      WRITE(11,REC=1) G(:,:)
      CLOSE(10)
      CLOSE(11)
    ENDDO
  ELSE
    WRITE(NOWDAY,'(I4.4)') WDAY
    OPEN(UNIT=10,&
    FILE=TRIM(DATPAS)//TRIM(FNDIVS)//TRIM(NOWDAY)//TRIM(ADDON),&
    FORM='UNFORMATTED',ACCESS='DIRECT',&
    RECL=((2*NN+1-MM)*MM+NN+1)*8,&
    CONVERT='BIG_ENDIAN',STATUS='OLD')
    READ(10,REC=1) S(:)
    WRITE(*,*) 'NOW CONVERTED DATA IS',WDAY,'[DAY]'
    CALL SXTS2G(MM,NM,NN,IM,JM,S,G,IT,T,P,R,JC,W,0_8)
    OPEN(UNIT=11,&
    FILE=TRIM(DATPAS)//TRIM(FNDIVG)//TRIM(NOWDAY)//TRIM(ADDON),&
    FORM='UNFORMATTED',ACCESS='DIRECT',RECL=JM*IM*8,&
    CONVERT='BIG_ENDIAN',STATUS='REPLACE')
    WRITE(11,REC=1) G(:,:)
    CLOSE(10)
    CLOSE(11)
  ENDIF

  IF(ALCONV) THEN
    DO I=0,DAY
      WRITE(NOWDAY,'(I4.4)') I
      OPEN(UNIT=10,&
      FILE=TRIM(DATPAS)//TRIM(FNDPHS)//TRIM(NOWDAY)//TRIM(ADDON),&
      FORM='UNFORMATTED',ACCESS='DIRECT',&
      RECL=((2*NN+1-MM)*MM+NN+1)*8,&
      CONVERT='BIG_ENDIAN',STATUS='OLD')
      READ(10,REC=1) S(:)
      WRITE(*,*) 'NOW CONVERTED DATA IS',I,'STEP'
      CALL SXTS2G(MM,NM,NN,IM,JM,S,G,IT,T,P,R,JC,W,0_8)
      OPEN(UNIT=11,&
      FILE=TRIM(DATPAS)//TRIM(FNDPHG)//TRIM(NOWDAY)//TRIM(ADDON),&
      FORM='UNFORMATTED',ACCESS='DIRECT',RECL=JM*IM*8,&
      CONVERT='BIG_ENDIAN',STATUS='REPLACE')
      WRITE(11,REC=1) G(:,:)
      CLOSE(10)
      CLOSE(11)
    ENDDO
  ELSE
    WRITE(NOWDAY,'(I4.4)') WDAY
    OPEN(UNIT=10,&
    FILE=TRIM(DATPAS)//TRIM(FNDPHS)//TRIM(NOWDAY)//TRIM(ADDON),&
    FORM='UNFORMATTED',ACCESS='DIRECT',&
    RECL=((2*NN+1-MM)*MM+NN+1)*8,&
    CONVERT='BIG_ENDIAN',STATUS='OLD')
    READ(10,REC=1) S(:)
    WRITE(*,*) 'NOW CONVERTED DATA IS',WDAY,'[DAY]'
    CALL SXTS2G(MM,NM,NN,IM,JM,S,G,IT,T,P,R,JC,W,0_8)
    OPEN(UNIT=11,&
    FILE=TRIM(DATPAS)//TRIM(FNDPHG)//TRIM(NOWDAY)//TRIM(ADDON),&
    FORM='UNFORMATTED',ACCESS='DIRECT',RECL=JM*IM*8,&
    CONVERT='BIG_ENDIAN',STATUS='REPLACE')
    WRITE(11,REC=1) G(:,:)
    CLOSE(10)
    CLOSE(11)
  ENDIF

  CALL MXFREE(PP)
  CALL MXFREE(PG)
  CALL MXFREE(PW)

END PROGRAM MAIN
